"""add channel + channel_video tables

Revision ID: aa1dc5896559
Revises: beb66710df84
Create Date: 2026-05-18 19:53:50.991967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1dc5896559'
down_revision: Union[str, None] = 'beb66710df84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('handle', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('accent_color', sa.String(length=16), nullable=True),
    sa.Column('last_synced_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_external_id'), 'channel', ['external_id'], unique=False)
    op.create_index(op.f('ix_channel_owner_id'), 'channel', ['owner_id'], unique=False)
    op.create_table('channel_video',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'external_id', name='uq_channel_video_external_id')
    )
    op.create_index(op.f('ix_channel_video_channel_id'), 'channel_video', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_video_channel_id'), table_name='channel_video')
    op.drop_table('channel_video')
    op.drop_index(op.f('ix_channel_owner_id'), table_name='channel')
    op.drop_index(op.f('ix_channel_external_id'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
